import React from 'react';

export default function TermsPage() {
  return (
    <div className="container py-5 max-w-800 mx-auto">
      <div className="glass-card p-4 p-md-5 border">
        <span className="badge bg-secondary text-white px-3 py-1 mb-2">TERMS & CONDITIONS</span>
        <h2 className="fw-extrabold text-navy mb-4">Terms of Service</h2>
        <p className="text-muted">
          By purchasing a number or entering a draw on Yalfal Online Eta, you agree to these Terms.
        </p>

        <h5 className="fw-bold text-navy mt-4">1. Age & Legal Capacity</h5>
        <p className="text-muted">
          You affirm that you are at least 18 years old and legally permitted to participate under Ethiopian regulations.
        </p>

        <h5 className="fw-bold text-navy mt-4">2. Ticket Confirmation & Payments</h5>
        <p className="text-muted">
          Selecting a number reserves it temporarily pending payment review. Only upon administrative approval 
          of a valid CBE or Telebirr receipt does the ticket become confirmed. Rejected payments release the number back to the pool.
        </p>

        <h5 className="fw-bold text-navy mt-4">3. Finality of Draws</h5>
        <p className="text-muted mb-0">
          Draw results generated by our cryptographic engine are final, permanent, and immutable. 
          Prizes are paid out according to the advertised schedule (1st: 10k, 2nd: 1k, 3rd: 500 ETB).
        </p>
      </div>
    </div>
  );
}
